services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: fastapi run --reload app/main.py
    develop:
      watch:  
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          ignore:
            .venv/
        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
